import { NextResponse, type NextRequest } from 'next/server';
import {
  adminTotpRequired,
  applyAuthCookies,
  createSession,
  verifyAdminTotp,
  verifyPassword,
} from '../../../../lib/auth';
import { enforceRateLimit } from '../../../../lib/rate-limit';

function getClientKey(request: NextRequest) {
  return request.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || 'unknown';
}

function getLoginErrorMessage(error: unknown) {
  if (!(error instanceof Error)) {
    return '登录失败，请稍后重试。';
  }

  if (
    error.message === 'Missing ADMIN_PASSWORD_HASH' ||
    error.message === 'ADMIN_PASSWORD_HASH must be generated by the provided script.'
  ) {
    return '管理员密码哈希配置无效。请使用 `npm run hash-password -- "your-password"` 重新生成，并在 `.env.local` 中将 `$` 写成 `\\$`。';
  }

  if (
    error.message === 'Missing ADMIN_TOTP_JSON' ||
    error.message === 'Invalid ADMIN_TOTP_JSON' ||
    error.message === 'ADMIN_TOTP_JSON must be a plain object.' ||
    error.message === 'ADMIN_TOTP_JSON.current is required.' ||
    error.message === 'ADMIN_TOTP_JSON.previous must be an array when provided.'
  ) {
    return '管理员 TOTP 配置无效。请设置 `ADMIN_TOTP_JSON`，形如 `{\"current\":\"BASE32SECRET\",\"period\":30,\"digits\":6,\"window\":1}`。';
  }

  return '登录失败，请稍后重试。';
}

export async function POST(request: NextRequest) {
  try {
    const limiter = await enforceRateLimit(`login:${getClientKey(request)}`, 5, 60_000);
    if (!limiter.ok) {
      return NextResponse.json(
        { ok: false, error: { message: '登录尝试过多，请稍后再试。' } },
        { status: 429, headers: { 'Retry-After': String(Math.ceil(limiter.retryAfterMs / 1000)) } },
      );
    }

    const body = (await request.json()) as { password?: string; totpToken?: string };
    const password = typeof body.password === 'string' ? body.password : '';
    const totpToken = typeof body.totpToken === 'string' ? body.totpToken.trim() : '';

    if (!password) {
      return NextResponse.json(
        { ok: false, error: { message: '缺少密码。' } },
        { status: 422 },
      );
    }

    if (!verifyPassword(password)) {
      return NextResponse.json(
        { ok: false, error: { message: '密码错误。' } },
        { status: 401 },
      );
    }

    const totpRequired = adminTotpRequired();
    let authMethod: 'password' | 'password+totp' | 'password+totp-dev-bypass' = 'password';

    if (totpRequired) {
      if (!totpToken) {
        return NextResponse.json(
          { ok: false, error: { message: '缺少 TOTP 验证码。' } },
          { status: 422 },
        );
      }

      if (!verifyAdminTotp(totpToken)) {
        return NextResponse.json(
          { ok: false, error: { message: 'TOTP 验证码无效或已过期。' } },
          { status: 401 },
        );
      }

      authMethod = 'password+totp';
    } else if (totpToken) {
      if (!verifyAdminTotp(totpToken)) {
        return NextResponse.json(
          { ok: false, error: { message: 'TOTP 验证码无效或已过期。' } },
          { status: 401 },
        );
      }

      authMethod = 'password+totp';
    } else {
      authMethod = 'password+totp-dev-bypass';
    }

    const response = NextResponse.json({ ok: true });
    applyAuthCookies(response, createSession(authMethod));
    return response;
  } catch (error) {
    console.error('Admin login failed.', error);
    return NextResponse.json(
      { ok: false, error: { message: getLoginErrorMessage(error) } },
      { status: 500 },
    );
  }
}
