import { NextResponse, type NextRequest } from 'next/server';
import {
  adminTotpRequired,
  applyAuthCookies,
  createSession,
  verifyAdminTotp,
  verifyPassword,
} from '../../../../lib/auth';
import { getClientKey } from '../../../../lib/client-key';
import { enforceRateLimit } from '../../../../lib/rate-limit';

const GENERIC_LOGIN_ERROR = '登录失败，请稍后重试。';

function isConfigurationError(error: unknown) {
  if (!(error instanceof Error)) return false;
  return (
    error.message === 'Missing ADMIN_PASSWORD_HASH' ||
    error.message === 'ADMIN_PASSWORD_HASH must be generated by the provided script.' ||
    error.message === 'Missing ADMIN_TOTP_JSON' ||
    error.message === 'Invalid ADMIN_TOTP_JSON' ||
    error.message === 'ADMIN_TOTP_JSON must be a plain object.' ||
    error.message === 'ADMIN_TOTP_JSON.current is required.' ||
    error.message === 'ADMIN_TOTP_JSON.previous must be an array when provided.' ||
    error.message === 'Missing SESSION_SECRET'
  );
}

export async function POST(request: NextRequest) {
  try {
    // Per-IP bucket — caps any single (possibly spoofed) X-Forwarded-For.
    const perIpLimiter = await enforceRateLimit(`login:${getClientKey(request)}`, 5, 60_000);
    if (!perIpLimiter.ok) {
      return NextResponse.json(
        { ok: false, error: { message: '登录尝试过多，请稍后再试。' } },
        { status: 429, headers: { 'Retry-After': String(Math.ceil(perIpLimiter.retryAfterMs / 1000)) } },
      );
    }

    // Global bucket — defense against header rotation. Even if an attacker
    // varies X-Forwarded-For on every request, they cannot exceed this cap.
    // The threshold is generous enough to allow a few admins on the same
    // egress IP to retry without false positives, but small enough that an
    // online brute force still hits a wall.
    const globalLimiter = await enforceRateLimit('login:global', 30, 60_000);
    if (!globalLimiter.ok) {
      return NextResponse.json(
        { ok: false, error: { message: '登录尝试过多，请稍后再试。' } },
        { status: 429, headers: { 'Retry-After': String(Math.ceil(globalLimiter.retryAfterMs / 1000)) } },
      );
    }

    const body = (await request.json()) as { password?: string; totpToken?: string };
    const password = typeof body.password === 'string' ? body.password : '';
    const totpToken = typeof body.totpToken === 'string' ? body.totpToken.trim() : '';

    if (!password) {
      return NextResponse.json(
        { ok: false, error: { message: '缺少密码。' } },
        { status: 422 },
      );
    }

    if (!verifyPassword(password)) {
      return NextResponse.json(
        { ok: false, error: { message: '密码错误。' } },
        { status: 401 },
      );
    }

    const totpRequired = adminTotpRequired();
    let authMethod: 'password' | 'password+totp' | 'password+totp-dev-bypass' = 'password';

    if (totpRequired) {
      if (!totpToken) {
        return NextResponse.json(
          { ok: false, error: { message: '缺少 TOTP 验证码。' } },
          { status: 422 },
        );
      }

      if (!verifyAdminTotp(totpToken)) {
        return NextResponse.json(
          { ok: false, error: { message: 'TOTP 验证码无效或已过期。' } },
          { status: 401 },
        );
      }

      authMethod = 'password+totp';
    } else if (totpToken) {
      if (!verifyAdminTotp(totpToken)) {
        return NextResponse.json(
          { ok: false, error: { message: 'TOTP 验证码无效或已过期。' } },
          { status: 401 },
        );
      }

      authMethod = 'password+totp';
    } else {
      authMethod = 'password+totp-dev-bypass';
    }

    const response = NextResponse.json({ ok: true });
    applyAuthCookies(response, createSession(authMethod));
    return response;
  } catch (error) {
    // Log the full reason server-side so operators can still diagnose
    // misconfiguration; never reflect internal hints to the client.
    if (isConfigurationError(error)) {
      console.error('[admin/login] configuration error:', (error as Error).message);
    } else {
      console.error('[admin/login] unexpected error:', error);
    }
    return NextResponse.json(
      { ok: false, error: { message: GENERIC_LOGIN_ERROR } },
      { status: 500 },
    );
  }
}
