'use client';

import { useEffect, useState } from 'react';
import { Copy, Plus, UserRoundX } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

type Member = { id: string; email: string; role: 'owner' | 'editor'; status: 'pending' | 'active' | 'disabled'; createdAt: string; updatedAt: string };
export default function MembersPageClient({ csrfToken }: { csrfToken: string }) {
  const [members, setMembers] = useState<Member[]>([]); const [email, setEmail] = useState(''); const [open, setOpen] = useState(false); const [inviting, setInviting] = useState(false);
  const load = async () => { const response = await fetch('/api/admin/members', { cache: 'no-store' }); const json = await response.json(); if (response.ok && json.ok) setMembers(json.data.members); };
  useEffect(() => { let cancelled = false; void fetch('/api/admin/members', { cache: 'no-store' }).then((response) => response.json().then((json) => ({ response, json }))).then(({ response, json }) => { if (!cancelled && response.ok && json.ok) setMembers(json.data.members); }); return () => { cancelled = true; }; }, []);
  const invite = async () => { setInviting(true); try { const response = await fetch('/api/admin/members', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-csrf-token': csrfToken }, body: JSON.stringify({ email }) }); const json = await response.json(); if (!response.ok || !json.ok) throw new Error(json.error?.message); await navigator.clipboard.writeText(json.data.invitationUrl); toast.success('邀请链接已复制，72 小时内有效。'); setEmail(''); setOpen(false); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : '创建邀请失败。'); } finally { setInviting(false); } };
  const setStatus = async (member: Member, status: 'active' | 'disabled') => { try { const response = await fetch(`/api/admin/members/${member.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json', 'x-csrf-token': csrfToken }, body: JSON.stringify({ status }) }); const json = await response.json(); if (!response.ok || !json.ok) throw new Error(json.error?.message); toast.success(status === 'disabled' ? '账户已停用，私密配置已删除。' : '账户已重新启用。'); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : '更新失败。'); } };
  return <main className="p-5 lg:p-8"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-tight">成员</h1><p className="mt-2 text-sm text-muted-foreground">只能管理账号与权限。成员内容、仓库和凭据始终不可见。</p></div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button><Plus />邀请编辑</Button>} /><DialogContent><DialogHeader><DialogTitle>邀请编辑</DialogTitle><DialogDescription>系统会生成一条可复制、仅能使用一次且 72 小时后失效的邀请链接。</DialogDescription></DialogHeader><div className="grid gap-2"><Label htmlFor="member-email">邮箱地址</Label><Input id="member-email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></div><DialogFooter><Button onClick={() => void invite()} disabled={inviting}>{inviting ? '创建中…' : <><Copy />创建并复制链接</>}</Button></DialogFooter></DialogContent></Dialog></div><div className="overflow-x-auto border"><table className="w-full min-w-[44rem] text-sm"><thead className="border-b text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="p-4 font-medium">邮箱</th><th className="p-4 font-medium">角色</th><th className="p-4 font-medium">状态</th><th className="p-4 font-medium">创建时间</th><th className="p-4 font-medium"><span className="sr-only">操作</span></th></tr></thead><tbody>{members.map((member) => <tr key={member.id} className="border-b last:border-0"><td className="p-4 font-medium">{member.email}</td><td className="p-4">{member.role === 'owner' ? '唯一管理员' : '编辑'}</td><td className="p-4"><span className={member.status === 'active' ? 'text-primary' : 'text-muted-foreground'}>{member.status === 'active' ? '活跃' : member.status === 'pending' ? '待接受邀请' : '已停用'}</span></td><td className="p-4 text-muted-foreground">{new Date(member.createdAt).toLocaleDateString('zh-CN')}</td><td className="p-4 text-right">{member.role === 'editor' ? <Button size="sm" variant={member.status === 'disabled' ? 'outline' : 'destructive'} onClick={() => void setStatus(member, member.status === 'disabled' ? 'active' : 'disabled')}>{member.status === 'disabled' ? '重新启用' : <><UserRoundX />停用</>}</Button> : <span className="text-xs text-muted-foreground">受保护</span>}</td></tr>)}</tbody></table></div></main>;
}
