import { randomBytes, createHmac, timingSafeEqual, scryptSync } from 'node:crypto';
import { cookies } from 'next/headers';
import type { NextRequest, NextResponse } from 'next/server';

const SESSION_COOKIE = 'arsvine_admin_session';
const CSRF_COOKIE = 'arsvine_admin_csrf';
const SESSION_TTL_SECONDS = 60 * 60 * 24 * 7;

type AdminSession = {
  sub: 'admin';
  exp: number;
  csrf: string;
  sig: string;
};

function getSessionSecret() {
  const secret = process.env.SESSION_SECRET?.trim();
  if (!secret) {
    throw new Error('Missing SESSION_SECRET');
  }
  return secret;
}

function signSession(sub: string, exp: number, csrf: string) {
  return createHmac('sha256', getSessionSecret())
    .update(`${sub}:${exp}:${csrf}`)
    .digest('base64url');
}

function encodeSession(session: AdminSession) {
  return Buffer.from(JSON.stringify(session), 'utf8').toString('base64url');
}

function decodeSession(value: string) {
  try {
    return JSON.parse(Buffer.from(value, 'base64url').toString('utf8')) as AdminSession;
  } catch {
    return null;
  }
}

export function createSession() {
  const csrf = randomBytes(18).toString('base64url');
  const exp = Date.now() + SESSION_TTL_SECONDS * 1000;
  const session: AdminSession = {
    sub: 'admin',
    exp,
    csrf,
    sig: signSession('admin', exp, csrf),
  };

  return {
    value: encodeSession(session),
    csrf,
    exp,
  };
}

function isSessionValid(session: AdminSession | null): session is AdminSession {
  if (!session || session.sub !== 'admin' || session.exp <= Date.now()) {
    return false;
  }

  const expected = signSession(session.sub, session.exp, session.csrf);
  const left = Buffer.from(session.sig);
  const right = Buffer.from(expected);

  if (left.length !== right.length) {
    return false;
  }

  return timingSafeEqual(left, right);
}

export function getSessionFromRequest(request: NextRequest) {
  const raw = request.cookies.get(SESSION_COOKIE)?.value;
  const session = raw ? decodeSession(raw) : null;
  return isSessionValid(session) ? session : null;
}

export async function getSessionFromCookieStore() {
  const cookieStore = await cookies();
  const raw = cookieStore.get(SESSION_COOKIE)?.value;
  const session = raw ? decodeSession(raw) : null;
  return isSessionValid(session) ? session : null;
}

export function applyAuthCookies(response: NextResponse, session: ReturnType<typeof createSession>) {
  const secure = process.env.NODE_ENV === 'production';

  response.cookies.set(SESSION_COOKIE, session.value, {
    httpOnly: true,
    secure,
    sameSite: 'lax',
    path: '/',
    maxAge: SESSION_TTL_SECONDS,
  });

  response.cookies.set(CSRF_COOKIE, session.csrf, {
    httpOnly: false,
    secure,
    sameSite: 'lax',
    path: '/',
    maxAge: SESSION_TTL_SECONDS,
  });
}

export function clearAuthCookies(response: NextResponse) {
  const secure = process.env.NODE_ENV === 'production';
  response.cookies.set(SESSION_COOKIE, '', {
    httpOnly: true,
    secure,
    sameSite: 'lax',
    path: '/',
    maxAge: 0,
  });
  response.cookies.set(CSRF_COOKIE, '', {
    httpOnly: false,
    secure,
    sameSite: 'lax',
    path: '/',
    maxAge: 0,
  });
}

export function verifyCsrf(request: NextRequest, session: AdminSession) {
  const headerToken = request.headers.get('x-csrf-token')?.trim();
  const cookieToken = request.cookies.get(CSRF_COOKIE)?.value?.trim();
  return Boolean(headerToken && cookieToken && headerToken === cookieToken && headerToken === session.csrf);
}

export function verifyPassword(password: string) {
  const encoded = process.env.ADMIN_PASSWORD_HASH?.trim();
  if (!encoded) {
    throw new Error('Missing ADMIN_PASSWORD_HASH');
  }

  const match = /^scrypt\$([^$]+)\$([^$]+)$/.exec(encoded);
  if (!match) {
    throw new Error('ADMIN_PASSWORD_HASH must be generated by the provided script.');
  }

  const [, salt, expectedHash] = match;
  const actualHash = scryptSync(password, salt, 64).toString('base64url');
  const left = Buffer.from(actualHash);
  const right = Buffer.from(expectedHash);

  if (left.length !== right.length) {
    return false;
  }

  return timingSafeEqual(left, right);
}
